### ISSUE TITLE
Hello, can this model handle 5D data of type (B, C, D, H, W)?

### ISSUE THREAD

**Issue by ILVHYY** [jacklishufan/Mamba-ND#4]

**Comment by ILVHYY** [comment]
Hello, can this model handle 5D data of type (B, C, D, H, W)?

**Comment by jacklishufan** [comment]
Hi, is B the batch dimension and C the channel dimension? If so, then your data is actually 3D and we can handle it just like we can handle video data with size (B,C,T,H,W), where T is time
